name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Documentation
      run: |
        sphinx-build -b html docs/source docs/build/

    - name: Commit and Stash Documentation
      run: |
        git add -f docs/build/
        git stash

    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Cleanup Old Folders
      run: |
        rm -rf _static/
        rm -rf _modules/
        rm -rf _sources/
        rm -rf examples/
        rm -rf modules/

    - name: Deploy to gh-pages
      run: |
        git stash pop
        mv -f docs/build/* .
        rm -rf docs/build
        git add .
        git commit -m "Auto update docs"
        git push
